// 本文件由 update/fetch.js 自动生成，请勿手改；数据来自各来源。
window.JOBS = [
  {
    "company": "【示例】星河科技",
    "title": "前端开发实习生",
    "city": "北京",
    "category": "互联网",
    "salary": "200-300/天",
    "education": "本科",
    "experience": "在校/应届",
    "deadline": "2026-09-30",
    "link": "https://example.com/job/1",
    "source": "校招官网",
    "type": "实习"
  },
  {
    "company": "【示例】云图数据",
    "title": "数据分析师（校招）",
    "city": "上海",
    "category": "互联网",
    "salary": "15-22K",
    "education": "本科",
    "experience": "应届",
    "deadline": "2026-10-15",
    "link": "https://example.com/job/2",
    "source": "企业招聘页",
    "type": "校招"
  },
  {
    "company": "【示例】远见咨询",
    "title": "商业分析实习生",
    "city": "广州",
    "category": "金融",
    "salary": "180-260/天",
    "education": "本科",
    "experience": "在校/应届",
    "deadline": "2026-09-20",
    "link": "https://example.com/job/3",
    "source": "校招官网",
    "type": "实习"
  },
  {
    "company": "【示例】新光传媒",
    "title": "内容运营（社招）",
    "city": "深圳",
    "category": "传媒",
    "salary": "10-16K",
    "education": "大专",
    "experience": "1-3年",
    "deadline": "2026-12-01",
    "link": "https://example.com/job/4",
    "source": "企业招聘页",
    "type": "社招"
  },
  {
    "company": "【示例】恒信制造",
    "title": "供应链管理培训生",
    "city": "苏州",
    "category": "制造",
    "salary": "9-13K",
    "education": "本科",
    "experience": "应届",
    "deadline": "2026-11-10",
    "link": "https://example.com/job/5",
    "source": "校招官网",
    "type": "校招"
  },
  {
    "company": "【示例】智联医疗",
    "title": "医学事务专员",
    "city": "杭州",
    "category": "医疗",
    "salary": "12-18K",
    "education": "硕士",
    "experience": "应届",
    "deadline": "2026-10-31",
    "link": "https://example.com/job/6",
    "source": "企业招聘页",
    "type": "校招"
  },
  {
    "company": "【示例】方圆教育",
    "title": "课程产品经理（实习）",
    "city": "北京",
    "category": "教育",
    "salary": "200-280/天",
    "education": "本科",
    "experience": "在校/应届",
    "deadline": "2026-09-25",
    "link": "https://example.com/job/7",
    "source": "校招官网",
    "type": "实习"
  },
  {
    "company": "【示例】蓝海游戏",
    "title": "游戏策划实习生",
    "city": "上海",
    "category": "互联网",
    "salary": "220-300/天",
    "education": "本科",
    "experience": "在校/应届",
    "deadline": "2026-10-20",
    "link": "https://example.com/job/8",
    "source": "企业招聘页",
    "type": "实习"
  },
  {
    "company": "【示例】绿野农业",
    "title": "农业技术销售",
    "city": "成都",
    "category": "制造",
    "salary": "8-12K",
    "education": "大专",
    "experience": "1-3年",
    "deadline": "2026-12-15",
    "link": "https://example.com/job/9",
    "source": "社招官网",
    "type": "社招"
  },
  {
    "company": "【示例】明德研究院",
    "title": "行业研究员（校招）",
    "city": "北京",
    "category": "金融",
    "salary": "14-20K",
    "education": "硕士",
    "experience": "应届",
    "deadline": "2026-11-05",
    "link": "https://example.com/job/10",
    "source": "校招官网",
    "type": "校招"
  },
  {
    "company": "舜宇集团有限公司",
    "title": "自动化设备技术员",
    "city": "浙江",
    "category": "其他",
    "salary": "6-8K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/SfjsyPeLGg8ryJgcWv3dRy/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "玳能科技（杭州）有限公司",
    "title": "储备干部",
    "city": "浙江",
    "category": "其他",
    "salary": "6.5-9K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/QKtsdreJeqRBLUHUwudEjk/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "外商独资/外企代表处",
    "type": "校招"
  },
  {
    "company": "玳能科技（杭州）有限公司",
    "title": "机械检验",
    "city": "浙江",
    "category": "其他",
    "salary": "6.5-9K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/Sun8vz9HqUpJ3tJUvUECQY/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "外商独资/外企代表处",
    "type": "校招"
  },
  {
    "company": "台州吉利汽车制造有限公司",
    "title": "物料配送员",
    "city": "江苏",
    "category": "其他",
    "salary": "5-8K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/U3Q57B19BEVr3LusR5kba6/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "台州吉利汽车制造有限公司",
    "title": "厂内物流员",
    "city": "江苏",
    "category": "其他",
    "salary": "5-8K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/Ve54VKLScTtYVsi4Wh1pWu/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "台州吉利汽车制造有限公司",
    "title": "物流操作工",
    "city": "浙江",
    "category": "其他",
    "salary": "5-8K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/X98BouDtb4kk8Dc7YcJyvB/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "玳能科技（杭州）有限公司",
    "title": "机加工",
    "city": "浙江",
    "category": "其他",
    "salary": "6.5-9K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/AaRPfE2U5EPZKFBG7caHRo/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "外商独资/外企代表处",
    "type": "校招"
  },
  {
    "company": "玳能科技（杭州）有限公司",
    "title": "生产技工",
    "city": "浙江",
    "category": "其他",
    "salary": "6.5-9K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/J1kSvE82ZKCyWBnfQYPKxa/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "外商独资/外企代表处",
    "type": "校招"
  },
  {
    "company": "玳能科技（杭州）有限公司",
    "title": "仓管员",
    "city": "浙江",
    "category": "其他",
    "salary": "6.5-9K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/GysouULWzDvzgZ28AgHy4Y/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "外商独资/外企代表处",
    "type": "校招"
  },
  {
    "company": "永城市耀莹汽车服务有限公司",
    "title": "汽修钣金学徒",
    "city": "山东",
    "category": "其他",
    "salary": "3-5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/C2cQZhQUENuFJR4wGbQnSy/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "永城市耀莹汽车服务有限公司",
    "title": "汽修学徒",
    "city": "山东",
    "category": "其他",
    "salary": "3-5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/NH7kKZU4xNLuDaehCs8npP/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "永城市耀莹汽车服务有限公司",
    "title": "车身装调学徒",
    "city": "山东",
    "category": "其他",
    "salary": "3-5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/MQ847jBMPymt9KjaSHwRrQ/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "永城市耀莹汽车服务有限公司",
    "title": "车身拆装学徒",
    "city": "山东",
    "category": "其他",
    "salary": "3-5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/97uC2iXuc1nqG49UhPkKDQ/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "永城市耀莹汽车服务有限公司",
    "title": "车身撕裂学徒",
    "city": "山东",
    "category": "其他",
    "salary": "3-5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3o4VxSws5rNVqPYALm7dWk/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "绍兴市越城区海虹舫海鲜大酒店有限公司",
    "title": "餐饮实习生",
    "city": "浙江",
    "category": "其他",
    "salary": "3.5-5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/KExNhjpK53MmL33JhLA2zd/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "实习"
  },
  {
    "company": "绍兴市越城区海虹舫海鲜大酒店有限公司",
    "title": "传菜实习生",
    "city": "浙江",
    "category": "其他",
    "salary": "3.5-5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/FA9PLvJ1qZ1kUvYk6iXFiK/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "实习"
  },
  {
    "company": "绍兴市越城区海虹舫海鲜大酒店有限公司",
    "title": "后厨实习生",
    "city": "浙江",
    "category": "其他",
    "salary": "3.5-5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/7A74oeBfve8rN1mBhUdTbo/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "实习"
  },
  {
    "company": "绍兴市越城区海虹舫海鲜大酒店有限公司",
    "title": "迎宾实习生",
    "city": "浙江",
    "category": "其他",
    "salary": "3.5-5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/XAN9CFLwCMz5YNsRZi4jXk/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "实习"
  },
  {
    "company": "绍兴市越城区海虹舫海鲜大酒店有限公司",
    "title": "前厅实习生",
    "city": "浙江",
    "category": "其他",
    "salary": "3.5-5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/T8aJBB4rS4DaGkQFyjjUNo/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "实习"
  },
  {
    "company": "扬州嵘泰精密压铸有限公司",
    "title": "压铸工",
    "city": "江苏",
    "category": "其他",
    "salary": "7.5-9.5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/YTj9hUa2Lz3WF8X5mfQ5La/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "股份制企业",
    "type": "校招"
  },
  {
    "company": "四川麒正建筑工程有限公司",
    "title": "现场质检员",
    "city": "重庆",
    "category": "其他",
    "salary": "4-6K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/57tvRVFue4Q2UWzPp4gEPy/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "邯郸市齐创制冷设备销售有限公司",
    "title": "门店运营",
    "city": "河北",
    "category": "其他",
    "salary": "3-5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/GybxrzM7Ciw53fC8msCXE5/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "邯郸市齐创制冷设备销售有限公司",
    "title": "工程专员",
    "city": "河北",
    "category": "其他",
    "salary": "3-6K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/AjGkXjqarRv3VkyVrjz592/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "上海美迪西生物医药股份有限公司",
    "title": "病理学家",
    "city": "上海",
    "category": "其他",
    "salary": "10-15K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/27K9pah92caLwSxmC5YZ53/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "泛林半导体（上海）有限公司",
    "title": "技术类",
    "city": "广东",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2Jthp6NgGrH6g56YkDh6k5/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "浙江京兰环保科技有限公司",
    "title": "助理工艺设计工程师",
    "city": "浙江",
    "category": "其他",
    "salary": "8-10K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2QNmg6ruTtu1KSqHCJT9kJ/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "广东阿道夫个人护理用品有限公司",
    "title": "渠道策略管培生",
    "city": "广东",
    "category": "其他",
    "salary": "6-8K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2SkmpHVKYLmz9geGhTbgb3/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "上海玖熠半导体科技有限公司",
    "title": "软件验证工程师",
    "city": "上海",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2bbHq7xN78ch7z9JJrQkPr/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "上海赛而微微电子科技有限公司",
    "title": "现场应用工程师",
    "city": "上海",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2gqKNjiGoKdwtWqnLJgMmm/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "上市公司",
    "type": "校招"
  },
  {
    "company": "青芯半导体科技（上海）有限公司",
    "title": "前端设计工程师",
    "city": "上海",
    "category": "其他",
    "salary": "0-0K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2x5exNfmhuzdQiftfipqEE/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "广东阿道夫个人护理用品有限公司",
    "title": "设计管培生",
    "city": "广东",
    "category": "其他",
    "salary": "6-8K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/34S2RmuiSR5potCd4wU1KH/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "芯盟科技有限公司",
    "title": "质量工程师",
    "city": "上海",
    "category": "其他",
    "salary": "0-0K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3gFXkXyd5FkRpBLg5Vqkbs/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "合资企业",
    "type": "校招"
  },
  {
    "company": "鹤壁海昌智能科技股份有限公司",
    "title": "机器人算法工程师",
    "city": "河南",
    "category": "其他",
    "salary": "8-10K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3zB1QXxiRD4YPWm5vYuWzv/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "中国电建集团核电工程有限公司",
    "title": "机械工程师（能源电力）",
    "city": "山东",
    "category": "其他",
    "salary": "6-8K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4QEY5jrnSQ4g4sUEKE3NzL/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "珠海基石科技有限公司",
    "title": "装备与自动化工程师",
    "city": "广东",
    "category": "其他",
    "salary": "10.5-15K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4iYrYmHh5n8kkUUSWsRtyQ/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "聚芯医疗科技(珠海)有限公司",
    "title": "算法工程师（脑机接口方向）",
    "city": "广东",
    "category": "其他",
    "salary": "5.5-6.5K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4qBWCQjWLo6xwQWhrJwEMr/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "浙江京兰环保科技有限公司",
    "title": "助理自控工程师",
    "city": "浙江",
    "category": "其他",
    "salary": "8-10K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4sVgmVzCeG3Ady6BD67oHB/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "博通集成（上海）股份有限公司",
    "title": "嵌入式软件工程师",
    "city": "上海",
    "category": "其他",
    "salary": "0-0K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4zYBCZhCrJxfsWCXcCXrcw/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "上市公司",
    "type": "校招"
  },
  {
    "company": "广东嘉腾机器人自动化有限公司",
    "title": "解决方案工程师",
    "city": "广东",
    "category": "其他",
    "salary": "10-20K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5JYitSo96eNbYv1oAouokM/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "深圳市石犀科技有限公司",
    "title": "产品经理/主管",
    "city": "广东",
    "category": "其他",
    "salary": "10-15K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5LqccGydVWLhvtazzYwx2e/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "杭州海康威视数字技术股份有限公司",
    "title": "【2027校园招聘】销售工程师",
    "city": "浙江",
    "category": "其他",
    "salary": "11-18K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5uJNfuy6RYcNnzPQ9LBgEz/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "北京大圣光华教育科技集团有限公司",
    "title": "大圣光华教育集团2027秋招线上宣讲会\n圣星云集 光华等你",
    "city": "山东",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5v4wsePugftmpDByFa3Gy4/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "中建装饰绿创科技（武汉）有限公司",
    "title": "物资管理岗",
    "city": "湖北",
    "category": "其他",
    "salary": "8-10K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/69oeSreocvc5LkQG4P19af/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "上海玖熠半导体科技有限公司",
    "title": "ai软件工程师",
    "city": "上海",
    "category": "其他",
    "salary": "0-0K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/6KKznNrkJgUidrwwgDwgqZ/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "中国东方电气集团有限公司",
    "title": "工程管理岗（安全）",
    "city": "四川",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/6MXXqfyD8ic3RL6MJx1wWE/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "浙江博沃电气有限公司",
    "title": "外贸运营助理",
    "city": "浙江",
    "category": "其他",
    "salary": "3.5-4.5K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/6bPdbue98XWtP2Lps9BgHR/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "芯联集成电路制造股份有限公司",
    "title": "研究类",
    "city": "浙江",
    "category": "其他",
    "salary": "0-0K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/6za4Y9Y9VaPMauXv5vumnk/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "青芯半导体科技（上海）有限公司",
    "title": "物理设计工程师",
    "city": "上海",
    "category": "其他",
    "salary": "0-0K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/7H4BRpuACz9uMTBQ9y1Lsd/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "灿芯半导体（上海）股份有限公司",
    "title": "模拟电路设计与验证工程师",
    "city": "上海",
    "category": "其他",
    "salary": "0-0K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/8gFgSqW4aYPqXEt9T25Tc/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "深圳市石犀科技有限公司",
    "title": "售前/售后咨询",
    "city": "广东",
    "category": "其他",
    "salary": "10-15K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/8m3kQnCPtHeiqDsFNt8Xw8/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  }
];
