// 本文件由 update/fetch.js 自动生成，请勿手改；数据来自各来源。
window.JOBS = [
  {
    "company": "【示例】星河科技",
    "title": "前端开发实习生",
    "city": "北京",
    "category": "互联网",
    "salary": "200-300/天",
    "education": "本科",
    "experience": "在校/应届",
    "deadline": "2026-09-30",
    "link": "https://example.com/job/1",
    "source": "校招官网",
    "type": "实习"
  },
  {
    "company": "【示例】云图数据",
    "title": "数据分析师（校招）",
    "city": "上海",
    "category": "互联网",
    "salary": "15-22K",
    "education": "本科",
    "experience": "应届",
    "deadline": "2026-10-15",
    "link": "https://example.com/job/2",
    "source": "企业招聘页",
    "type": "校招"
  },
  {
    "company": "【示例】远见咨询",
    "title": "商业分析实习生",
    "city": "广州",
    "category": "金融",
    "salary": "180-260/天",
    "education": "本科",
    "experience": "在校/应届",
    "deadline": "2026-09-20",
    "link": "https://example.com/job/3",
    "source": "校招官网",
    "type": "实习"
  },
  {
    "company": "【示例】新光传媒",
    "title": "内容运营（社招）",
    "city": "深圳",
    "category": "传媒",
    "salary": "10-16K",
    "education": "大专",
    "experience": "1-3年",
    "deadline": "2026-12-01",
    "link": "https://example.com/job/4",
    "source": "企业招聘页",
    "type": "社招"
  },
  {
    "company": "【示例】恒信制造",
    "title": "供应链管理培训生",
    "city": "苏州",
    "category": "制造",
    "salary": "9-13K",
    "education": "本科",
    "experience": "应届",
    "deadline": "2026-11-10",
    "link": "https://example.com/job/5",
    "source": "校招官网",
    "type": "校招"
  },
  {
    "company": "【示例】智联医疗",
    "title": "医学事务专员",
    "city": "杭州",
    "category": "医疗",
    "salary": "12-18K",
    "education": "硕士",
    "experience": "应届",
    "deadline": "2026-10-31",
    "link": "https://example.com/job/6",
    "source": "企业招聘页",
    "type": "校招"
  },
  {
    "company": "【示例】方圆教育",
    "title": "课程产品经理（实习）",
    "city": "北京",
    "category": "教育",
    "salary": "200-280/天",
    "education": "本科",
    "experience": "在校/应届",
    "deadline": "2026-09-25",
    "link": "https://example.com/job/7",
    "source": "校招官网",
    "type": "实习"
  },
  {
    "company": "【示例】蓝海游戏",
    "title": "游戏策划实习生",
    "city": "上海",
    "category": "互联网",
    "salary": "220-300/天",
    "education": "本科",
    "experience": "在校/应届",
    "deadline": "2026-10-20",
    "link": "https://example.com/job/8",
    "source": "企业招聘页",
    "type": "实习"
  },
  {
    "company": "【示例】绿野农业",
    "title": "农业技术销售",
    "city": "成都",
    "category": "制造",
    "salary": "8-12K",
    "education": "大专",
    "experience": "1-3年",
    "deadline": "2026-12-15",
    "link": "https://example.com/job/9",
    "source": "社招官网",
    "type": "社招"
  },
  {
    "company": "【示例】明德研究院",
    "title": "行业研究员（校招）",
    "city": "北京",
    "category": "金融",
    "salary": "14-20K",
    "education": "硕士",
    "experience": "应届",
    "deadline": "2026-11-05",
    "link": "https://example.com/job/10",
    "source": "校招官网",
    "type": "校招"
  },
  {
    "company": "江西云杉智能科技有限公司",
    "title": "工程技术员（电气）",
    "city": "江西",
    "category": "其他",
    "salary": "3.5-4.5K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3jw9ASaTTRoycCJE6ipha3/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "江西云杉智能科技有限公司",
    "title": "品质技术员",
    "city": "江西",
    "category": "其他",
    "salary": "3.5-4.5K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/QZrY6HDEfxPz9nc8pM2jKY/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "招商局港口集团股份有限公司",
    "title": "工程技术类岗位",
    "city": "广东",
    "category": "其他",
    "salary": "10-15K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4DAUAS7Nq3Vj1dyuR42ZVx/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "四川天味食品集团股份有限公司",
    "title": "人力管培生",
    "city": "四川",
    "category": "其他",
    "salary": "8-12K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/67qLBu19eYRru9o3XJBPJ8/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "四川天味食品集团股份有限公司",
    "title": "研发管培生（香精香料方向）",
    "city": "四川",
    "category": "其他",
    "salary": "8-10K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/FfG9paYCSv9dpEuaPyJwaF/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "招商局港口集团股份有限公司",
    "title": "信息科学类岗位",
    "city": "广东",
    "category": "其他",
    "salary": "10-15K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/Rjeu1GHoEUQ8uzb1zV6UEt/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "招商局港口集团股份有限公司",
    "title": "交通运输类岗位",
    "city": "广东",
    "category": "其他",
    "salary": "10-15K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/X2kDJYUPLvC3SJXRAoCo8Q/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "招商局港口集团股份有限公司",
    "title": "经济管理类岗位",
    "city": "广东",
    "category": "其他",
    "salary": "10-15K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/voBg4XnxvvVAs76M6psAy/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "河北万景文旅集团有限公司",
    "title": "舞蹈演员",
    "city": "河北",
    "category": "其他",
    "salary": "3-5K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/34HCfsRywYDExM8u5cnx5s/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "河北万景文旅集团有限公司",
    "title": "演员（语言类）",
    "city": "河北",
    "category": "其他",
    "salary": "3-4K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3TgYmjccpBRai6RpCxf1gX/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "福建金德尚黄金有限公司",
    "title": "首饰制作员",
    "city": "福建",
    "category": "其他",
    "salary": "4.5-5.5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4z7Q3WHBeXi8jBawBZSUti/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "安徽繁星能源科技有限公司",
    "title": "产品开发技术员",
    "city": "安徽",
    "category": "其他",
    "salary": "5-8K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/54z1tqr5j5d5U4kZKeE14F/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "华融金融租赁股份有限公司",
    "title": "华融金租2027届秋季校园招聘公告",
    "city": "浙江",
    "category": "其他",
    "salary": "10-10K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5FrgHSzDSvVba9GVLihBht/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "安徽繁星能源科技有限公司",
    "title": "质量检验员",
    "city": "安徽",
    "category": "其他",
    "salary": "5-8K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5KbkbFjFbSAAWc3f8CWA4D/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "重庆市龙彪机械制造有限公司",
    "title": "注塑模具安装调试",
    "city": "重庆",
    "category": "其他",
    "salary": "5.5-6.5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5hEgJ8SDPRQNBrCFYvfQJq/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "常州学益得教育科技有限公司",
    "title": "课程顾问",
    "city": "江苏",
    "category": "其他",
    "salary": "8-10K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5zSgVa4ypEoMHK7TYeW6TA/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "科尔卡诺集团有限公司",
    "title": "平面设计师",
    "city": "浙江",
    "category": "其他",
    "salary": "8-10K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/65rYVJFHoQ2Wg4zHa4GQMX/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "河北世纪学程教育科技有限公司",
    "title": "网络运营管理",
    "city": "全国",
    "category": "其他",
    "salary": "4-6K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/6EnGagK6sWeFB4vq7rBKNN/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "常熟华新特殊钢有限公司",
    "title": "管培生-常熟",
    "city": "江苏",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/6NxY3whoo5x5bM8utqJ3gp/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "迈得医疗工业设备股份有限公司",
    "title": "人事储备干部",
    "city": "浙江",
    "category": "其他",
    "salary": "8-10K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/6ZeeEpedqrCQ7U3MPoS5Q5/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "科尔卡诺集团有限公司",
    "title": "产品/策划专员",
    "city": "浙江",
    "category": "其他",
    "salary": "8-10K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/6a3gTGmHNoxQjTYoi9j6eC/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "中国石油化工股份有限公司茂名分公司",
    "title": "2027年校园招聘炼油化工装置电气管理储备岗",
    "city": "广东",
    "category": "其他",
    "salary": "15-99.9K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/6e9xZcpSa7bAXpZGWAN1Rx/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "上海邦成生物工程有限公司",
    "title": "QC/QA管培生",
    "city": "上海",
    "category": "其他",
    "salary": "5.5-6.5K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/6x2icP7tR9h2rG7VG3eJ34/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "宁波德业科技股份有限公司",
    "title": "测试助理工程师",
    "city": "浙江",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/7523wuGoBDve7bRqrgHAjg/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "国泰海通证券股份有限公司湖南分公司",
    "title": "业务经理",
    "city": "湖南",
    "category": "其他",
    "salary": "6-7K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/7DrAFKiQ9p1jMDF151Nyic/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "芜湖市弋江区北辰精学教育咨询有限公司",
    "title": "中学教师",
    "city": "安徽",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/7FzrAxqviGGFLm7vCUekEW/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "宁波德业科技股份有限公司",
    "title": "电气工程师",
    "city": "浙江",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/7VM3K7o393WZr677WSJABq/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "兴唐通信科技有限公司",
    "title": "数据所（兴唐公司）2027届校园招聘",
    "city": "北京",
    "category": "其他",
    "salary": "10-10K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/7gJPq1qf2DpcgqioScNXCy/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "中国石油化工股份有限公司茂名分公司",
    "title": "2027年校园招聘炼油化工装置仪表运行岗",
    "city": "广东",
    "category": "其他",
    "salary": "10.5-15K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/82ufJcwqVDrj2xebDuvSNT/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "北京缘起宏福科技有限公司",
    "title": "云计算运维工程师",
    "city": "北京",
    "category": "其他",
    "salary": "6-8K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/8BrrrRC96owYmn8Hi4Rwm6/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "河北世纪学程教育科技有限公司",
    "title": "市场主管",
    "city": "河北",
    "category": "其他",
    "salary": "8-10K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/8FtUjwsRSEQCy2KMXUWwTh/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "大博医疗科技股份有限公司",
    "title": "体系专员",
    "city": "福建",
    "category": "其他",
    "salary": "6.5-7.5K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/8Gfo9VyhxKHdRoBSRcB2F/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "深圳捷牛科技有限公司",
    "title": "助理光学工程师",
    "city": "广东",
    "category": "其他",
    "salary": "15-99.9K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/8Lb3W7nDXEBqPN4ADrSszx/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "中国石油化工股份有限公司茂名分公司",
    "title": "2027年校园招聘信息化管理储备岗",
    "city": "广东",
    "category": "其他",
    "salary": "15-99.9K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/8fA6iTmScKSsXCtHZd9ojc/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "宁波德业科技股份有限公司",
    "title": "采购",
    "city": "浙江",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/8qdjEtBAzP6d9CozWrnz7F/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "中国石油化工股份有限公司茂名分公司",
    "title": "2027年校园招聘信息技术运行岗",
    "city": "广东",
    "category": "其他",
    "salary": "15-99.9K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/A4EuBV1fQYMZcNYLAvD9pH/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "义乌市富聪贸易有限公司",
    "title": "葡语外贸业务员",
    "city": "浙江",
    "category": "其他",
    "salary": "6.5-7.5K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/ALyLW9J75Zv398NXBsZrDh/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "福建金德尚黄金有限公司",
    "title": "数控编程/数控操机",
    "city": "福建",
    "category": "其他",
    "salary": "4.5-5.5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/B9ddf81Kaf8CPNs7gRfAYx/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "重庆三生有幸养老公寓有限公司",
    "title": "养老护理员",
    "city": "重庆",
    "category": "其他",
    "salary": "3.5-4.5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/BPJHvgUbyXSbcDWc2seDz1/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "深圳捷牛科技有限公司",
    "title": "助理电气工程师",
    "city": "广东",
    "category": "其他",
    "salary": "10.5-15K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/BenUGxmRvztsBYDiMH8WjR/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "迈得医疗工业设备股份有限公司",
    "title": "财务储备干部",
    "city": "浙江",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/Bgp7sL4H16jtdyHSNhC98/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "北京中公科技发展有限公司石家庄分公司",
    "title": "学习管理师",
    "city": "河北",
    "category": "其他",
    "salary": "4-6K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/C2p1Q78PAgnwwPcGFq9wEC/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "河北世纪学程教育科技有限公司",
    "title": "教务管理",
    "city": "河北",
    "category": "其他",
    "salary": "3-4K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/C4Dup2CoVj62kB6VX9jEc7/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "重庆市龙彪机械制造有限公司",
    "title": "总工程师助理",
    "city": "重庆",
    "category": "其他",
    "salary": "5.5-6.5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/C5NXhSdgUMNb2drkCraUaz/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "大博医疗科技股份有限公司",
    "title": "管培生（项目管理/研发）",
    "city": "福建",
    "category": "其他",
    "salary": "8.5-9.5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/C5zBuuXZNmSe8gHfntHEJA/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "宁波德业科技股份有限公司",
    "title": "人事专员",
    "city": "浙江",
    "category": "其他",
    "salary": "5-8K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/C8JS6VQdJrrQHEs9oVc8jx/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "宁波德业科技股份有限公司",
    "title": "策划",
    "city": "浙江",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/CEFgJt7GYbMA9xLAqgHytK/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "上海邦成生物工程有限公司",
    "title": "国内销售岗位",
    "city": "上海",
    "category": "其他",
    "salary": "5.5-6.5K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/Cnwzq8GcHv45fnzTUQzF9T/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "河北世纪学程教育科技有限公司",
    "title": "网络运营管理",
    "city": "全国",
    "category": "其他",
    "salary": "4-6K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/CwGZ6k7xKt4P3tWCsUxLcG/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "北京佐佑管理顾问有限公司",
    "title": "咨询顾问",
    "city": "北京",
    "category": "其他",
    "salary": "10-10K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/DDMUYv41JdW16H7q2LF9ub/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  }
];
