// 本文件由 update/fetch.js 自动生成，请勿手改；数据来自各来源。
window.JOBS = [
  {
    "company": "【示例】星河科技",
    "title": "前端开发实习生",
    "city": "北京",
    "category": "互联网",
    "salary": "200-300/天",
    "education": "本科",
    "experience": "在校/应届",
    "deadline": "2026-09-30",
    "link": "https://example.com/job/1",
    "source": "校招官网",
    "type": "实习"
  },
  {
    "company": "【示例】云图数据",
    "title": "数据分析师（校招）",
    "city": "上海",
    "category": "互联网",
    "salary": "15-22K",
    "education": "本科",
    "experience": "应届",
    "deadline": "2026-10-15",
    "link": "https://example.com/job/2",
    "source": "企业招聘页",
    "type": "校招"
  },
  {
    "company": "【示例】远见咨询",
    "title": "商业分析实习生",
    "city": "广州",
    "category": "金融",
    "salary": "180-260/天",
    "education": "本科",
    "experience": "在校/应届",
    "deadline": "2026-09-20",
    "link": "https://example.com/job/3",
    "source": "校招官网",
    "type": "实习"
  },
  {
    "company": "【示例】新光传媒",
    "title": "内容运营（社招）",
    "city": "深圳",
    "category": "传媒",
    "salary": "10-16K",
    "education": "大专",
    "experience": "1-3年",
    "deadline": "2026-12-01",
    "link": "https://example.com/job/4",
    "source": "企业招聘页",
    "type": "社招"
  },
  {
    "company": "【示例】恒信制造",
    "title": "供应链管理培训生",
    "city": "苏州",
    "category": "制造",
    "salary": "9-13K",
    "education": "本科",
    "experience": "应届",
    "deadline": "2026-11-10",
    "link": "https://example.com/job/5",
    "source": "校招官网",
    "type": "校招"
  },
  {
    "company": "【示例】智联医疗",
    "title": "医学事务专员",
    "city": "杭州",
    "category": "医疗",
    "salary": "12-18K",
    "education": "硕士",
    "experience": "应届",
    "deadline": "2026-10-31",
    "link": "https://example.com/job/6",
    "source": "企业招聘页",
    "type": "校招"
  },
  {
    "company": "【示例】方圆教育",
    "title": "课程产品经理（实习）",
    "city": "北京",
    "category": "教育",
    "salary": "200-280/天",
    "education": "本科",
    "experience": "在校/应届",
    "deadline": "2026-09-25",
    "link": "https://example.com/job/7",
    "source": "校招官网",
    "type": "实习"
  },
  {
    "company": "【示例】蓝海游戏",
    "title": "游戏策划实习生",
    "city": "上海",
    "category": "互联网",
    "salary": "220-300/天",
    "education": "本科",
    "experience": "在校/应届",
    "deadline": "2026-10-20",
    "link": "https://example.com/job/8",
    "source": "企业招聘页",
    "type": "实习"
  },
  {
    "company": "【示例】绿野农业",
    "title": "农业技术销售",
    "city": "成都",
    "category": "制造",
    "salary": "8-12K",
    "education": "大专",
    "experience": "1-3年",
    "deadline": "2026-12-15",
    "link": "https://example.com/job/9",
    "source": "社招官网",
    "type": "社招"
  },
  {
    "company": "【示例】明德研究院",
    "title": "行业研究员（校招）",
    "city": "北京",
    "category": "金融",
    "salary": "14-20K",
    "education": "硕士",
    "experience": "应届",
    "deadline": "2026-11-05",
    "link": "https://example.com/job/10",
    "source": "校招官网",
    "type": "校招"
  },
  {
    "company": "东莞市黄江镇宣传教育文体旅游办公室",
    "title": "实习采编、摄像、后期制作",
    "city": "广东",
    "category": "其他",
    "salary": "0-0K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2BNXyNqg173hzz2JKAAVDz/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "实习"
  },
  {
    "company": "东莞市黄江镇宣传教育文体旅游办公室",
    "title": "短视频文案策划",
    "city": "广东",
    "category": "其他",
    "salary": "0-0K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/GKkWUf1sMuAXwQF13VcGXb/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "赫章县河镇彝族苗族乡人民政府",
    "title": "安全生产辅助实习生",
    "city": "贵州",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/165HuGY3qeq1qBvXt8HhwV/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "实习"
  },
  {
    "company": "上海叠纸科技有限公司",
    "title": "叠纸游戏校招",
    "city": "上海",
    "category": "其他",
    "salary": "15-99.9K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/171mRnEvWuK34n4RDzSCS9/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "赫章县河镇彝族苗族乡人民政府",
    "title": "资料台账实习生",
    "city": "贵州",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/282HTRKYsAvardM8Bu7QyA/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "实习"
  },
  {
    "company": "上海微电机研究所(中国电子科技集团公司第二十一研究所)",
    "title": "机器人装配调试实习生",
    "city": "上海",
    "category": "其他",
    "salary": "1-1K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2eVo5yE2mVpW1Zp3vSS4Ld/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "机关/事业单位/非营利机构",
    "type": "实习"
  },
  {
    "company": "武汉渲奇数字艺术有限公司",
    "title": "3D动画师",
    "city": "湖北",
    "category": "其他",
    "salary": "4.5-5.5K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3H44gN5BdKznikZzUtMagj/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "新东方教育科技集团有限公司",
    "title": "教学质控实习生",
    "city": "河南",
    "category": "其他",
    "salary": "1-1K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3hEYt7dF3X2yMGuG1Sc6df/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "实习"
  },
  {
    "company": "南京瑞源生物技术有限公司",
    "title": "HRBP",
    "city": "江苏",
    "category": "其他",
    "salary": "8-10K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/47d6y2hMp81jAKCY2ZsuJL/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "厦门鑫雷发工贸有限公司",
    "title": "外贸业务员",
    "city": "福建",
    "category": "其他",
    "salary": "5-9K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4CadwTMC6XeXtXJqfdQuh8/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "孝感联兴文化用品有限公司",
    "title": "带货主播",
    "city": "湖北",
    "category": "其他",
    "salary": "4.5-5.5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2UMebfRVQWTzFHdu1m7gvi/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "苏州能讯高能半导体有限公司",
    "title": "制程质量工程师",
    "city": "安徽",
    "category": "其他",
    "salary": "8.5-9.5K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2agTWU1TMhUuDymosQgiXk/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "国电南京自动化股份有限公司",
    "title": "工程设计师（热控方向）",
    "city": "江苏",
    "category": "其他",
    "salary": "0-0K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2bXer4AfypRp9Vmr36WZuo/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "上市公司",
    "type": "校招"
  },
  {
    "company": "四川东材科技集团股份有限公司",
    "title": "销售工程师",
    "city": "四川",
    "category": "其他",
    "salary": "8-1K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2doxtHuBovrvpHuUeZrPsY/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "南京因克斯智能科技有限公司",
    "title": "硬件工程师(高速信号方向)",
    "city": "江苏",
    "category": "其他",
    "salary": "12-22K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/2wUrZx4tLaUaJ5Huy7yhZz/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "深圳市亿道控股有限公司",
    "title": "智能制造管培生—品质管理方向",
    "city": "广东",
    "category": "其他",
    "salary": "8-1K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/31J2Z2XZczA6Vr352VCeNL/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "内蒙古顺丰速运有限公司",
    "title": "27届财务岗",
    "city": "内蒙古",
    "category": "其他",
    "salary": "6-8K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/35s5a6844bxCKu92Z5hgWz/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "内蒙古顺丰速运有限公司",
    "title": "27届经营管理岗（网点负责人方向）",
    "city": "内蒙古",
    "category": "其他",
    "salary": "6-8K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3Cne9kJXNStuaUEKxWjM5F/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "南京因克斯智能科技有限公司",
    "title": "算法工程师(SLAM方向)",
    "city": "江苏",
    "category": "其他",
    "salary": "12-22K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3CpLTXfM7DqUW7vFddVCbY/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "苏州能讯高能半导体有限公司",
    "title": "高级外延工程师",
    "city": "江苏",
    "category": "其他",
    "salary": "15-99.9K",
    "education": "博士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3EFm1455fN7h5wJQ46hAni/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "赫章县威奢乡人民政府",
    "title": "办公室实习生",
    "city": "贵州",
    "category": "其他",
    "salary": "0-0K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3HWPKtN8nBh7M999kqRbhJ/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "实习"
  },
  {
    "company": "锐钲(杭州)科技有限公司",
    "title": "测试开发工程师",
    "city": "四川",
    "category": "其他",
    "salary": "15-25K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3JBadgXwXWieGaNCWQjELx/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "苏州能讯高能半导体有限公司",
    "title": "半导体产品开发工程师",
    "city": "安徽",
    "category": "其他",
    "salary": "10.5-15K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3JHiWYkwBMwDCpdEBWHqYS/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "宜昌三峡人家文化旅游发展有限公司",
    "title": "舞蹈演员",
    "city": "湖北",
    "category": "其他",
    "salary": "5.5-6.5K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3SboYxkTPvgK8wFRDxB3gU/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "米哈游科技（上海）有限公司",
    "title": "米哈游27届秋季校招&amp;28届及以后全年实习招聘",
    "city": "上海",
    "category": "其他",
    "salary": "15-99.9K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3Zje17McJYCQZrdKwtxAvs/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "实习"
  },
  {
    "company": "万达商业管理集团有限公司武汉分公司",
    "title": "市场/营销",
    "city": "全国",
    "category": "其他",
    "salary": "6-8K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3jECfEd1nVc1Vbn9hMM5SG/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "深圳市亿道控股有限公司",
    "title": "产品经理",
    "city": "广东",
    "category": "其他",
    "salary": "12-20K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3xEYvcMawvEHW7fE6aCqD8/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "武汉光庭信息技术股份有限公司",
    "title": "智能导航开发工程师",
    "city": "湖北",
    "category": "其他",
    "salary": "9.5-10.5K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/3zMp4Jfua9UB1R2fZBaxfa/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "南宁鹏旭科技有限公司",
    "title": "出差代表",
    "city": "广西",
    "category": "其他",
    "salary": "5.5-6.5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4FqJ25yLTcsR1ULjTkEokU/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "武汉人才市场评荐有限公司",
    "title": "高中实习体育教师",
    "city": "湖北",
    "category": "其他",
    "salary": "4.5-5.5K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4GpgEtU1gmGu8m6WUtkBa1/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "实习"
  },
  {
    "company": "重庆长安汽车股份有限公司",
    "title": "汽车生产制造类岗位（国企）",
    "city": "重庆",
    "category": "其他",
    "salary": "6.5-7.5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4KtZW7oG55YEscZbkMwekc/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "平安银行股份有限公司上海分行",
    "title": "平安银行股份有限公司上海分行&amp;上海自贸试验区分行",
    "city": "上海",
    "category": "其他",
    "salary": "10.5-15K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4L9iqGicZuUcct6t5zr9t5/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "南京因克斯智能科技有限公司",
    "title": "硬件工程师",
    "city": "江苏",
    "category": "其他",
    "salary": "12-22K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4N6rt2w7WKsBFvieqoTTz6/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "南京因克斯智能科技有限公司",
    "title": "Agent开发工程师",
    "city": "江苏",
    "category": "其他",
    "salary": "12-22K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4T5gr5rkEiV5QTjarxVNRe/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "如果新能源科技（江苏）股份有限公司",
    "title": "项目管理工程师",
    "city": "江苏",
    "category": "其他",
    "salary": "15-99.9K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4gXqjuMkAbvPr11B6Mwyaq/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "万达商业管理集团有限公司武汉分公司",
    "title": "招商岗-武汉城市公司-万新生-27届",
    "city": "湖北",
    "category": "其他",
    "salary": "6.5-7.5K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4hmp5aw1YqVVc49SreRcG1/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "深圳市龙岗区保安服务有限公司",
    "title": "深圳地铁列车巡查员（包吃住）",
    "city": "广东",
    "category": "其他",
    "salary": "5.5-6.5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4oAaxyJSXd5qe7fp1socSq/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "广州小鹏汽车科技有限公司",
    "title": "新能源汽车销售实习生（27届校招+提成）",
    "city": "浙江",
    "category": "其他",
    "salary": "5-5K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4sXJWEMqo3YZRqUbee1kgF/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "实习"
  },
  {
    "company": "中国联合网络通信有限公司新疆维吾尔自治区分公司",
    "title": "【测试】岗位发布-勿投递",
    "city": "新疆",
    "category": "其他",
    "salary": "0-0K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4w45tCzS3B8Bje4ra6zfCa/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "中国能源建设集团辽宁电力勘测设计院有限公司",
    "title": "商务人员",
    "city": "辽宁",
    "category": "其他",
    "salary": "8-12K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4wrMoA9qr2LxuCxh5anVni/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "杭州泰格医药科技股份有限公司",
    "title": "CRC Intern-长沙（2027校招）",
    "city": "湖南",
    "category": "其他",
    "salary": "1-1K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/4zSvo3Vj7buvZiPtuQ9XRt/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "合资企业",
    "type": "校招"
  },
  {
    "company": "锐钲(杭州)科技有限公司",
    "title": "固件开发工程师",
    "city": "四川",
    "category": "其他",
    "salary": "15-25K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/57uRqJciP5KytEU6eUo6vg/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "如果新能源科技（江苏）股份有限公司",
    "title": "产品营销管培生",
    "city": "广东",
    "category": "其他",
    "salary": "10.5-15K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5ATQ7fo8huPgAcxD5JrCzd/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "其他",
    "type": "校招"
  },
  {
    "company": "哈尔滨市松北区松安社区卫生服务中心",
    "title": "公共卫生工作人员",
    "city": "黑龙江",
    "category": "其他",
    "salary": "0-0K",
    "education": "专科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5AknFTecv1c5vfgbwbtRe4/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "机关/事业单位/非营利机构",
    "type": "校招"
  },
  {
    "company": "湖北至宸人力资源服务有限公司",
    "title": "会计",
    "city": "湖北",
    "category": "其他",
    "salary": "5.5-6.5K",
    "education": "不限",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5B5cvUz79cZ1r7bjWAfVqz/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "包头聚信私募基金管理有限公司",
    "title": "投资助理",
    "city": "内蒙古",
    "category": "其他",
    "salary": "1-4K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5KDaUoyu6VxmeLu77y7Qqx/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "国有企业",
    "type": "校招"
  },
  {
    "company": "湖北美标汽车制冷系统有限公司",
    "title": "销售管培生",
    "city": "湖北",
    "category": "其他",
    "salary": "4.5-5.5K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5aWJzDXeTMPzVSS7gZmwe1/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "联欧希望教育管理（安徽）有限公司",
    "title": "驻外护士",
    "city": "全国",
    "category": "其他",
    "salary": "15-99.9K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5gnatZuRAAJ7ewFrgxurMh/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  },
  {
    "company": "中国科学院长春光学精密机械与物理研究所",
    "title": "中国科学院长春光学精密机械与物理研究所(长春光机所)2026年秋季招聘公告",
    "city": "吉林",
    "category": "其他",
    "salary": "10-99.9K",
    "education": "硕士及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5ivQvSgKAagsSBcPVq1YEE/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "",
    "type": "校招"
  },
  {
    "company": "内蒙古顺丰速运有限公司",
    "title": "27届经营管理岗（网点负责人方向）",
    "city": "内蒙古",
    "category": "其他",
    "salary": "6-8K",
    "education": "本科及以上",
    "experience": "—",
    "deadline": "",
    "link": "https://job.ncss.cn/student/jobs/5rX3PDpKrSTSstPA7GYiuz/detail.html",
    "source": "国家大学生就业服务平台",
    "nature": "民营企业",
    "type": "校招"
  }
];
